replicaCount: 1

image:
  repository: 182790204459.dkr.ecr.us-east-1.amazonaws.com/workshop-preview-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: preview.example.com

resources:
  requests:
    cpu: 50m
    memory: 64Mi

  limits:
    cpu: 250m
    memory: 256Mi